# -*- coding: utf-8 -*-
"""Compare Face.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O1KyS3sRXhyD_FCbH4pmcaqSgT3jktNv
"""

!pip install dlib==19.18.0

pip install face-recognition

pip install opencv-python

import cv2
import numpy as np
import face_recognition

import cv2
from google.colab.patches import cv2_imshow
import face_recognition

imgelon_bgr = face_recognition.load_image_file('/content/drive/MyDrive/SEM 2/Self /Face Recognition/messi.jpeg')
imgelon_rgb = cv2.cvtColor(imgelon_bgr, cv2.COLOR_BGR2RGB)

# Display images using cv2_imshow
cv2_imshow(imgelon_bgr)
cv2_imshow(imgelon_rgb)

import cv2
import face_recognition
from google.colab.patches import cv2_imshow

imgelon = face_recognition.load_image_file('/content/drive/MyDrive/SEM 2/Self /Face Recognition/Jungkook.jpg')
imgelon_rgb = cv2.cvtColor(imgelon, cv2.COLOR_BGR2RGB)

# Finding face Location for drawing bounding boxes
face = face_recognition.face_locations(imgelon_rgb)[0]
copy = imgelon.copy()

# Drawing the Rectangle
cv2.rectangle(copy, (face[3], face[0]), (face[1], face[2]), (255, 0, 255), 2)

# Displaying images using cv2_imshow
cv2_imshow(copy)
cv2_imshow(imgelon)

train_elon_encodings = face_recognition.face_encodings(imgelon)[0]

import cv2
import face_recognition

# Load the training image
train_image = face_recognition.load_image_file('/content/drive/MyDrive/SEM 2/Self /Face Recognition/Jungkook.jpg')
train_image = cv2.cvtColor(train_image, cv2.COLOR_BGR2RGB)

# Obtain facial encodings for the training image
train_encode = face_recognition.face_encodings(train_image)[0]

# Load the test image
# test_image = face_recognition.load_image_file('/content/drive/MyDrive/SEM 2/Self /Face Recognition/Jungkook2.jpg')
test_image = face_recognition.load_image_file('/content/drive/MyDrive/SEM 2/Self /Face Recognition/messi.jpeg')

test_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2RGB)

# Obtain facial encodings for the test image
test_encode = face_recognition.face_encodings(test_image)[0]

# Compare facial encodings and print the result
result = face_recognition.compare_faces([train_encode], test_encode)
print(result)

import cv2
import face_recognition

# Load the training image
train_image = face_recognition.load_image_file('/content/drive/MyDrive/SEM 2/Self /Face Recognition/Jungkook.jpg')
train_image = cv2.cvtColor(train_image, cv2.COLOR_BGR2RGB)

# Obtain facial encodings for the training image
train_encode = face_recognition.face_encodings(train_image)[0]

# Load the test image
test_image = face_recognition.load_image_file('/content/drive/MyDrive/SEM 2/Self /Face Recognition/Jungkook2.jpg')

test_image = cv2.cvtColor(test_image, cv2.COLOR_BGR2RGB)

# Obtain facial encodings for the test image
test_encode = face_recognition.face_encodings(test_image)[0]

# Compare facial encodings and print the result
result = face_recognition.compare_faces([train_encode], test_encode)
print(result)